version: "3.9"
services:
  backend:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
